# Generated by Django 2.2.4 on 2019-08-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
